import React, { useState, useMemo } from 'react';
import { TriangleAlert } from 'lucide-react';
import { useTheme, getThemeColors } from '../contexts/ThemeContext';
import { translateUI } from '../utils/translation';
import type { Language } from '../utils/translation';
import { getNextDepartures, getDirectionIndex, hasTimetableData, getLineTimetable } from '../data/timetableData';
import type { RouteResult } from '../utils/routeFinder';
import { SEMANTIC, FS } from '../constants/ui';
import Button from './ui/atoms/Button';
import { L } from './legend/legendStyles';
import TrainTimeStepper from './ui/molecules/TrainTimeStepper';

interface TimetablePanelProps { routeResult: RouteResult | null; departureTime: string; onDepartureTimeChange: (t: string) => void; language?: Language; isMobile?: boolean; }
function addMinutes(timeStr: string, minutes: number): string { const [h,m]=timeStr.split(':').map(Number); const total=h*60+m+minutes; const norm=((total%1440)+1440)%1440; return `${String(Math.floor(norm/60)).padStart(2,'0')}:${String(norm%60).padStart(2,'0')}`; }
const TYPE_COLOR: Record<string,string>={'各停':'#555','普通':'#555','急行':'#d35400','快速':'#2980b9','快速アクティー':'#2980b9','特別快速':'#1a6ea8','準急':'#c0392b','快特':'#8e44ad','特急ロマンスカー':'#e74c3c'};
const typeColor=(t:string)=>TYPE_COLOR[t]??'#333';
const nowHHMM=()=>{const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};

const TimetablePanel: React.FC<TimetablePanelProps>=({routeResult,departureTime,onDepartureTimeChange,language='japanese',isMobile=false})=>{
 const {theme}=useTheme(); const colors=getThemeColors(theme); const [expandedSegments,setExpandedSegments]=useState<Set<number>>(new Set());
 const timeline=useMemo(()=>{if(!routeResult)return [];const result:any[]=[];let cumTime=0;for(let i=0;i<routeResult.segments.length;i++){const seg=routeResult.segments[i];if(seg.isWalkingTransfer){cumTime+=seg.walkingTime??5;continue;}const fromName=seg.stations[0]?.name??'';const toName=seg.stations[seg.stations.length-1]?.name??'';const depTime=addMinutes(departureTime,cumTime);const arrTime=addMinutes(departureTime,cumTime+seg.time);const dirIdx=getDirectionIndex(seg.routeKey,fromName,toName);result.push({segIndex:i,fromStation:fromName,toStation:toName,routeKey:seg.routeKey,routeName:seg.routeName,departTime:depTime,arriveTime:arrTime,segTime:seg.time,directionIndex:dirIdx,hasTimetable:hasTimetableData(seg.routeKey)});cumTime+=seg.time;}return result;},[routeResult,departureTime]);
 const toggleExpand=(i:number)=>setExpandedSegments(p=>{const n=new Set(p);n.has(i)?n.delete(i):n.add(i);return n;});
 const totalArriveTime=useMemo(()=>timeline.length?timeline[timeline.length-1].arriveTime:'',[timeline]);
 const dataVersionLabel=useMemo(()=>{for(const seg of timeline){const ld=getLineTimetable(seg.routeKey);if(ld)return{version:ld.dataVersion,updatedAt:ld.updatedAt};}return null;},[timeline]);
 const firstSegment=timeline[0];
 const stepTrain=(direction:-1|1)=>{if(!firstSegment?.hasTimetable){onDepartureTimeChange(addMinutes(departureTime,direction));return;}const probe=direction<0?addMinutes(departureTime,-180):addMinutes(departureTime,1);const deps=getNextDepartures(firstSegment.routeKey,firstSegment.fromStation,firstSegment.directionIndex,probe,direction<0?30:1);if(!deps.length)return;if(direction>0){onDepartureTimeChange(deps[0].time);return;}const current=departureTime;const earlier=deps.filter((d:any)=>d.time<current);if(earlier.length)onDepartureTimeChange(earlier[earlier.length-1].time);};
 if(!routeResult)return <div style={{padding:L.sp.xl,color:colors.textSecondary,fontSize:FS.body,textAlign:'center'}}>{translateUI('selectStationsPrompt',language)}</div>;
 return <div style={{backgroundColor:colors.surfaceElevated,color:colors.text,fontSize:FS.body,overflowY:'auto',maxHeight:isMobile?'calc(60vh - 88px)':'70vh'}}>
  <div style={{padding:`${L.sp.lg} ${L.sp.xl}`,borderBottom:`1px solid ${colors.borderLight}`,display:'flex',alignItems:'center',gap:L.sp.md,flexWrap:'wrap'}}>
   <span style={{fontWeight:'bold'}}>{translateUI('departureTime',language)}</span>
   <TrainTimeStepper value={departureTime} theme={theme} language={language} onPrevious={()=>stepTrain(-1)} onNext={()=>stepTrain(1)} onUseNow={()=>onDepartureTimeChange(nowHHMM())}/>
   <input aria-label={translateUI('departureTime',language)} type="time" value={departureTime} onChange={e=>onDepartureTimeChange(e.target.value)} style={{border:`1px solid ${colors.border}`,borderRadius:L.r.control,background:colors.surface,color:colors.text,padding:`${L.sp.xs} ${L.sp.sm}`,font:'inherit'}}/>
  </div>
  <div style={{padding:`${L.sp.md} 0`}}>{timeline.map((seg:any,idx:number)=>{const isExpanded=expandedSegments.has(seg.segIndex);const nextDeps=isExpanded&&seg.hasTimetable?getNextDepartures(seg.routeKey,seg.fromStation,seg.directionIndex,seg.departTime,12):[];const isLast=idx===timeline.length-1;return <React.Fragment key={seg.segIndex}>
   <div style={{padding:`${L.sp.sm} ${L.sp.xl}`,display:'flex',alignItems:'center',gap:L.sp.sm}}><span style={{width:8,height:8,borderRadius:'50%',backgroundColor:idx===0?SEMANTIC.departure:colors.primary}}/><strong>{seg.fromStation}</strong><strong style={{fontSize:FS.title,color:idx===0?SEMANTIC.departure:colors.primary,marginLeft:'auto'}}>{seg.departTime} {translateUI('departsLabel',language)}</strong></div>
   <div style={{padding:`${L.sp.xxs} ${L.sp.xl} ${L.sp.xxs} ${L.sp['4xl']}`,display:'flex',alignItems:'center',gap:L.sp.sm,flexWrap:'wrap'}}><div style={{width:2,height:24,backgroundColor:colors.borderLight,marginRight:L.sp.xs}}/><span style={{color:colors.textSecondary,fontSize:FS.caption}}>{seg.routeName}</span><span style={{backgroundColor:colors.surface,border:`1px solid ${colors.borderLight}`,borderRadius:L.r.control,padding:`0 ${L.sp.xs}`,fontSize:FS.caption,color:colors.textSecondary}}>{translateUI('approxMinutes',language,{time:seg.segTime})}</span>{seg.hasTimetable&&<Button theme={theme} variant="primary" size="sm" pressed={isExpanded} onClick={()=>toggleExpand(seg.segIndex)} styleOverride={{marginLeft:'auto'}}>{isExpanded?`▲ ${translateUI('close',language)}`:`▼ ${translateUI('timetableButton',language)}`}</Button>}</div>
   {isExpanded&&<div style={{margin:`${L.sp.xs} ${L.sp.xl} ${L.sp.xs} ${L.sp['4xl']}`,backgroundColor:colors.surface,border:`1px solid ${colors.borderLight}`,borderRadius:L.r.control,overflow:'hidden'}}><div style={{padding:`${L.sp.xs} ${L.sp.md}`,fontSize:FS.caption,color:colors.textSecondary,borderBottom:`1px solid ${colors.borderLight}`,backgroundColor:colors.surfaceElevated}}>{translateUI('departsAfterLabel',language,{station:seg.fromStation,time:seg.departTime,route:seg.routeName})}</div>{nextDeps.length===0?<div style={{padding:L.sp.md,color:colors.textSecondary,fontSize:FS.caption}}>{translateUI('noTimetableDataFound',language)}</div>:nextDeps.map((dep:any,di:number)=><button key={`${dep.time}-${di}`} type="button" onClick={()=>idx===0&&onDepartureTimeChange(dep.time)} style={{width:'100%',border:0,borderBottom:di<nextDeps.length-1?`1px solid ${colors.borderLight}`:'none',background:'transparent',color:colors.text,padding:`${L.sp.xs} ${L.sp.md}`,display:'flex',alignItems:'center',gap:L.sp.md,textAlign:'left',font:'inherit',cursor:idx===0?'pointer':'default'}}><strong style={{fontSize:FS.title,minWidth:45}}>{dep.time}</strong><span style={{fontSize:FS.caption,color:colors.onPrimary,backgroundColor:typeColor(dep.type),borderRadius:L.r.control,padding:`${L.sp.xxs} ${L.sp.xs}`,minWidth:28,textAlign:'center'}}>{dep.type}</span>{dep.platform&&<span style={{fontSize:FS.caption,color:colors.textSecondary}}>{dep.platform}</span>}<span style={{fontSize:FS.caption,color:colors.textSecondary}}>{dep.destination}{dep.toward?translateUI('towardDirection',language,{direction:dep.toward}):''}</span></button>)}</div>}
   {!isLast&&<div style={{padding:`0 ${L.sp.xl} 0 ${L.sp['4xl']}`,color:colors.textSecondary,fontSize:FS.caption}}>▼</div>}{isLast&&<div style={{padding:`${L.sp.sm} ${L.sp.xl}`,display:'flex',alignItems:'center',gap:L.sp.sm}}><span style={{width:8,height:8,borderRadius:'50%',backgroundColor:SEMANTIC.arrival}}/><strong>{seg.toStation}</strong><strong style={{fontSize:FS.title,color:SEMANTIC.arrival,marginLeft:'auto'}}>{totalArriveTime} {translateUI('arrivesLabel',language)}</strong></div>}
  </React.Fragment>;})}</div>
  {dataVersionLabel&&<div style={{padding:`${L.sp.md} ${L.sp.xl}`,borderTop:`1px solid ${colors.borderLight}`,fontSize:FS.caption,color:colors.textSecondary,lineHeight:1.5}}><TriangleAlert size={11} style={{verticalAlign:'text-bottom',marginRight:3}}/>{dataVersionLabel.version}{translateUI('approxNote',language)}<br/>{translateUI('timetableUpdatedAt',language,{date:dataVersionLabel.updatedAt})}　{translateUI('timetableDisclaimerNote',language)}</div>}
 </div>;
};
export default TimetablePanel;
